"""
Django settings for djcrm project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # ** Base Directory --> Core module


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9)ur_o^cq2fu2qanu@k=@)z(q=@=e#x_ldym3blzi8ymz&ql@e' # * Secret key to access the controls

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # * Keep it as false while it's in production

ALLOWED_HOSTS = []


# Application definition
# ! Default application 

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # * Installed application by the developer
    
    'leads'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# * Root urls djcrm---> urls file inside the djcrm

ROOT_URLCONF = 'djcrm.urls'

# Todo Templates settings --> like changing the root directory of default templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ! Used to deploy(app) synchronous app One way request and receving info
WSGI_APPLICATION = 'djcrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# * Database settings (development we're using dbsqlite3). (Production postgrese)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators
# ? Different password validator

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# * Static files (CSS, JavaScript, Images) --> Files that never change 
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# * Section for static files
# ? To setup the static files 3 things to configure in settings.py 1.STATIC_URL 2. STATICFILES_DIRS 3.STATIC_ROOT
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR, os.path.join(BASE_DIR, 'static')
]

STATIC_ROOT = 'static_root'



AUTH_USER_MODEL = 'leads.User'

# todo console email backends

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# ? Login redirect url

LOGIN_REDIRECT_URL = 'leads:lead_list'
LOGOUT_REDIRECT_URL = 'leads:lead_list'